version: "3.6"

services:
  jlinkster-registry:
    image: jhipster/jhipster-registry
    container_name: jlinkster-registry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=registry
      - SPRING_CLOUD_CONFIG_NAME=registry
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/jlinkster/config
